site_name: fortee2 help
site_url: https://help.fortee2.com
theme:
  name: readthedocs
  highlightjs: true
nav:
  - Home: index.md
  - How to:
    - start-a-game.md
  - Releases:
    - changelog/5.22.1/index.md
